import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "../src/lib/utils";
import { Toaster } from "sonner";
import { ThemeProvider } from "../src/providers/theme-provider";
import Footer from "../src/components/common/footer";
import Navigation from "../src/components/navigation/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <body
          className={cn(
            inter.variable,
            "bg-background font-sans text-foreground antialiased",
          )}
        >
          <div className="flex min-h-screen w-full flex-col">
            <Navigation />
            <div className="space-between mx-2 flex h-full flex-grow flex-col md:container">
              <main className="mx-2 my-8 h-full flex-grow md:mx-8 md:ml-16">
                {children}
              </main>

              <Toaster richColors closeButton />
            </div>
            <Footer />
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
