/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/geokoding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finn representasjonspunkt eller område for et spesifikt matrikkelnummer.
         * @description Finn representasjonspunkt eller område for et spesifikt matrikkelnummer. Matrikkelnummeret må ha formen "Kommunenr-Gårdsnr/Bruksnr/Festenr/Seksjonsnr" hvis festenr og seksjonsnr er aktuelt (seksjoner med eget uteareal, eller eiendommen den er seksjonert på). For eksempel ?matrikkelnummer=0301-223/60/0/3<p> Alternativt kan man oppgi nummerene individuelt. For eksempel  ?kommunenummer=0301&gardsnummer=223&bruksnummer=60</p>
         */
        get: {
            parameters: {
                query?: {
                    /** @description Den offisielle benevnelsen for en eiendom. Fullstendig matrikkelnummer består av kommunenummer, gardsnummer, bruksnummer, eventuelt festenummer, eventuelt seksjonsnummer, f.eks 3413-325/2 (grunneiendom), 3413-325/2/1 (festegrunn) eller 3413-6/501/0/2 (seksjon) */
                    matrikkelnummer?: string;
                    /** @description Angi som "true" for å hente ut område i stedet for kun representasjonspunktet.  Område er flater avgrenset av linjer som kan være eiendomsgrenser (av ulik kvalitet), men også hjelpelinjer der grenser mangler i matrikkelen.  For volumer over eller under bakken er område et «fotavtrykk». */
                    omrade?: boolean;
                    /** @description Kommunenummer bestående av fire tegn med ledende 0 om nødvendig. */
                    kommunenummer?: string;
                    /** @description Del av et matrikkelnummer */
                    gardsnummer?: number;
                    /** @description Del av et matrikkelnummer */
                    bruksnummer?: number;
                    /** @description Del av et matrikkelnummer */
                    festenummer?: number;
                    /** @description Del av et matrikkelnummer */
                    seksjonsnummer?: number;
                    /** @description Angi det koordinatsystemet som du ønsker at geometrien i returen skal transformeres til, oppgis som en SRID (altså tallene i en EPSG-kode, f.eks. 4258 eller 25833). Standard er 4258. 4258 er i praksis identisk med 4326. Hvis det bes om et annet koordinatsystem enn det som er standard for geojson (4326/4258) så inkluderes et CRS-element i en geojson-respons. */
                    utkoordsys?: number;
                    /** @description Vis kun de elementene du vil ha i returen. Kommaseparert liste med nøkler. For å hente ut underobjekter bruk "."-notasjon, f.eks. &filtrer=metadata.side */
                    filtrer?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeoKodingRespons"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/punkt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finn eiendommer nær et gitt geografisk punkt.
         * @description Gjør et geografisk søk etter de nærmeste eiendommene, dvs deres teiger eller anleggsprojeksjonsflate registrert i matrikkelsystemet. <p>For eksempel ?nord=60.5&ost=11.12&koordsys=4258&radius=1000</p>
         */
        get: {
            parameters: {
                query: {
                    /** @description Øst-koordinaten/Longitude */
                    ost: number;
                    /** @description Nord-koordinaten/Latitude */
                    nord: number;
                    /** @description Koordinatsystemet (EPSG) til koordinatene du søker med. Angis som en SRID, for eksempel 4258 eller 25833. */
                    koordsys: number;
                    /** @description Radius i antall meter som søket leter etter eiendommer i. Maksimum er 3000m. */
                    radius?: number;
                    /** @description Angi det koordinatsystemet som du ønsker at geometrien i returen skal transformeres til, oppgis som en SRID (altså tallene i en EPSG-kode, f.eks. 4258 eller 25833). Standard er 4258. 4258 er i praksis identisk med 4326. Hvis det bes om et annet koordinatsystem enn det som er standard for geojson (4326/4258) så inkluderes et CRS-element i en geojson-respons. */
                    utkoordsys?: number;
                    /** @description Vis kun de elementene du vil ha i returen. Kommaseparert liste med nøkler. For å hente ut underobjekter bruk "."-notasjon, f.eks. &filtrer=metadata.side */
                    filtrer?: string;
                    /** @description Antall treff per side. Minimum 1, maksimum 500. */
                    treffPerSide?: number;
                    /** @description Sidenummeret som skal vises i returen. Minimum 1, maksimum 500. */
                    side?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PunktRespons"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/punkt/omrader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returnerer GeoJSON med områder nær et gitt geografisk punkt.
         * @description Gjør et geografisk søk etter teigene til de nærmeste eiendommene, dvs deres teiger eller anleggsprojeksjonsflate registrert i matrikkelsystemet. Det returneres i form av en GeoJSON-featurecollection. <p>For eksempel ?nord=60.5&ost=11.12&koordsys=4258&radius=1000</p>
         */
        get: {
            parameters: {
                query: {
                    /** @description Øst-koordinaten/Longitude */
                    ost: number;
                    /** @description Nord-koordinaten/Latitude */
                    nord: number;
                    /** @description Koordinatsystemet (EPSG) til koordinatene du søker med. Angis som en SRID, for eksempel 4258 eller 25833. */
                    koordsys: number;
                    /** @description Radius i antall meter som søket leter etter eiendommer i. Maksimum er 3000m. */
                    radius?: number;
                    /** @description Angi det koordinatsystemet som du ønsker at geometrien i returen skal transformeres til, oppgis som en SRID (altså tallene i en EPSG-kode, f.eks. 4258 eller 25833). Standard er 4258. 4258 er i praksis identisk med 4326. Hvis det bes om et annet koordinatsystem enn det som er standard for geojson (4326/4258) så inkluderes et CRS-element i en geojson-respons. */
                    utkoordsys?: number;
                    /** @description Vis kun de elementene du vil ha i returen. Kommaseparert liste med nøkler. For å hente ut underobjekter bruk "."-notasjon, f.eks. &filtrer=metadata.side */
                    filtrer?: string;
                    /** @description Maks antall objekter i GeoJSON-featurecollection responsen. Maksimum er 500. */
                    maksTreff?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeoKodingRespons"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GeoJsonCoordinates: {
            coordinates?: unknown[];
            type?: string;
        };
        GeoKodingRespons: {
            crs?: components["schemas"]["GeojsonCrs"];
            features?: components["schemas"]["GeokodingGeoJson"][];
            type?: string;
        };
        GeojsonCrs: {
            properties?: components["schemas"]["GeojsonEpsg"];
            type?: string;
        };
        GeojsonEpsg: {
            name?: string;
        };
        GeokodingGeoJson: {
            geometry?: components["schemas"]["GeoJsonCoordinates"];
            properties?: components["schemas"]["GeokodingProperties"];
            type?: string;
        };
        GeokodingProperties: {
            /** @description Del av et matrikkelnummer */
            bruksnummer?: number;
            /** @description Del av et matrikkelnummer */
            festenummer?: number;
            /** @description Del av et matrikkelnummer */
            gardsnummer?: number;
            /** @description Angir om området er teigens eller anleggsprojeksjonens hovedteig/hovedflate. */
            "hovedomr\u00E5de"?: boolean;
            /** @description Kommunenummer bestående av fire tegn med ledende 0 om nødvendig. */
            kommunenummer?: string;
            /** @description Lokal identifikator, tildelt av dataleverandør/dataforvalter (her matrikkelsystemet, Kartverket). */
            lokalid?: number;
            /** @description Generert tekst ut fra hvilken matrikkelenhet teigen tilhører. Eventuelt flere matrikkelnummere skyldes manglende, uavklarte grenser eller uregistrert jordsameie. */
            matrikkelnummertekst?: string;
            /** @description Distanse i meter til punktet det ble søkt etter. */
            meterFraPunkt?: number;
            /** @description Grov klassifisering (trafikklys) av stedfestingsnøyaktighet. (Grønt = ok, gult = sjekk!, rødt = store mangler) */
            "n\u00F8yaktighetsklasseteig"?: string;
            /** @description Stedfesting/geometri hentes fra to objekttyper, teig eller anleggsprojeksjonsflate. Den siste er «fotavtrykk» av volumer som fins over eller under teiger på terrenget */
            objekttype?: string;
            /**
             * Format: date-time
             * @description dato for siste endring på data-objektet i matrikkelsystemet
             */
            oppdateringsdato?: string;
            /** @description Del av et matrikkelnummer */
            seksjonsnummer?: number;
            /** @description Teigen mangler indre avgrensing mellom de registrerte matrikkelnummerene */
            teigmedflerematrikkelenheter?: boolean;
            /** @description De registrerte matrikkelnummerene har andel i teigen */
            uregistrertjordsameie?: boolean;
        };
        Metadata: {
            /**
             * @description Sidenummeret som skal vises i returen. Minimum 1, maksimum 500.
             * @default 1
             */
            side: number;
            /** @description Søkestrengen som ble sendt inn til API-et. */
            sokeStreng?: string;
            /** @description Antall treff som søket returnerte. */
            totaltAntallTreff?: number;
            /**
             * @description Antall treff per side. Minimum 1, maksimum 500.
             * @default 10
             */
            treffPerSide: number;
            /** @description Viser treff fra objekt nummer X i responsen. */
            viserFra?: number;
            /** @description Viser treff til objekt nummer X i responsen. */
            viserTil?: number;
        };
        Punkt: {
            /** @description Del av et matrikkelnummer */
            bruksnummer?: number;
            /** @description Del av et matrikkelnummer */
            festenummer?: number;
            /** @description Del av et matrikkelnummer */
            gardsnummer?: number;
            /** @description Angir om området er teigens eller anleggsprojeksjonens hovedteig/hovedflate. */
            "hovedomr\u00E5de"?: boolean;
            /** @description Kommunenummer bestående av fire tegn med ledende 0 om nødvendig. */
            kommunenummer?: string;
            /** @description Lokal identifikator, tildelt av dataleverandør/dataforvalter (her matrikkelsystemet, Kartverket). */
            lokalid?: number;
            /** @description Generert tekst ut fra hvilken matrikkelenhet teigen tilhører. Eventuelt flere matrikkelnummere skyldes manglende, uavklarte grenser eller uregistrert jordsameie. */
            matrikkelnummertekst?: string;
            /** @description Distanse i meter til punktet det ble søkt etter. */
            meterFraPunkt?: number;
            /** @description Grov klassifisering (trafikklys) av stedfestingsnøyaktighet. (Grønt = ok, gult = sjekk!, rødt = store mangler) */
            "n\u00F8yaktighetsklasseteig"?: string;
            /** @description Stedfesting/geometri hentes fra to objekttyper, teig eller anleggsprojeksjonsflate. Den siste er «fotavtrykk» av volumer som fins over eller under teiger på terrenget */
            objekttype?: string;
            /**
             * Format: date-time
             * @description dato for siste endring på data-objektet i matrikkelsystemet
             */
            oppdateringsdato?: string;
            /** @description Punktet ligger innenfor teigens eller flatens avgrensing. */
            representasjonspunkt?: components["schemas"]["Representasjonspunkt"];
            /** @description Del av et matrikkelnummer */
            seksjonsnummer?: number;
            /** @description Teigen mangler indre avgrensing mellom de registrerte matrikkelnummerene */
            teigmedflerematrikkelenheter?: boolean;
            /** @description De registrerte matrikkelnummerene har andel i teigen */
            uregistrertjordsameie?: boolean;
        };
        PunktRespons: {
            eiendom?: components["schemas"]["Punkt"][];
            metadata?: components["schemas"]["Metadata"];
        };
        Representasjonspunkt: {
            /** @description Koordinatsystemet til representasjonspunktet, oppgis som en SRID (altså tall-delen av en EPSG-kode, f.eks. 4258 eller 25833). */
            koordsys?: number;
            nord?: number;
            "\u00F8st"?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
